SELECT
  1 AS `BUSINESS_ID`,
  1 AS `BUSINESS_NAME`,
  1 AS `BUSINESS_FOOD_MENU_CARD_ID`,
  1 AS `MENU_NAME`,
  1 AS `BUSINESS_PRODUCT_CATEGORY_ID`,
  1 AS `CATEGORY`,
  1 AS `PRODUCT_NAME`,
  1 AS `PRODUCT_DESCRIPTION`,
  1 AS `PRODUCT_PRICE`,
  1 AS `COMPARE_AS_PRICE`